Repository kalkih/simple-weather-card, pull requests merged in 2020-05, with the labels that each got.

#31 Add Dark Sky icon values and resolve issue when using custom icon-state
  src/main.js
  src/weather.js
Labels: bug, enhancement

#34 Add support for displaying air pressure
  README.md
  icons/pressure.svg
  src/main.js
  src/weather.js
Labels: enhancement

#33 Adopt new translation path #30
  src/weather.js
Labels: bug
